### ISSUE TITLE
All Products Null

### ISSUE THREAD

**Issue by Strvm** [dashnullify/shoppyapi#1]
Hi! I've been playing around with your API, orders seem to work fine but when I try to get all products I get this error:

Exception in thread "main" com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected NUMBER but was BEGIN_OBJECT at path $.quantity

Here is the full stacktrace:

`Exception in thread "main" com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected NUMBER but was BEGIN_OBJECT at path $.quantity
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:1003)
	at com.google.gson.Gson.fromJson(Gson.java:975)
	at me.unknown.shoppyapi.api.impl.ProductAPI.getAllProducts(ProductAPI.java:44)
	at me.unknown.shoppyapi.ShoppyAPI.getAllProducts(ShoppyAPI.java:55)
	at Test.main(Test.java:19)
Caused by: java.lang.IllegalStateException: Expected NUMBER but was BEGIN_OBJECT at path $.quantity
	at com.google.gson.internal.bind.JsonTreeReader.nextInt(JsonTreeReader.java:242)
	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:226)
	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:218)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	... 6 more
`

**Comment by dashnullify** [comment]
Hmm i didnt get this? might be because quantity is infinite ?

**Comment by Strvm** [comment]
Nope, I tweaked it a bit and it's because some variables aren't correct variable types to what the GSON is giving us. So for example, quantity isn't an int and gatewars and webhook_urls aren't Strings but Arrays.

**Comment by dashnullify** [comment]
ahhhhh i see ok, i will have to fix it later i cant right now

**Comment by Strvm** [comment]
Yep no worries just reporting the issue :) .

**Comment by Strvm** [comment]
Would it be possible to create an order with the API? Like create a new order and when its complete it returns the product?

**Comment by dashnullify** [comment]
I mean not really with Shoppys api. https://shoppy.dev/ i went off of there documents you could try https://shoppy.dev/#/payv2.

**Comment by Strvm** [comment]
Yea I saw their docs on  https://shoppy.dev/ . I also saw they had a v1 payment, I was just wondering if you had planned to implement this part of the API into ShoppyAPI.

**Comment by dashnullify** [comment]
I mean you can implement it if you want.

**Comment by Strvm** [comment]
Yea i've tried to implement it but unfortunately I get a HTTP responde code 422 (I'm kinda a newbie when it comes to HTTP requests. 

Here is the code i'm using:

`public void pay() throws Exception {
        LinkedHashMap<String,Object> arguments = new LinkedHashMap<>();
        arguments.put("title", "Test");
        arguments.put("value", 1);

        System.out.println(getGson().toJson(arguments));
        getHttpClient().post(BASE, getGson().toJson(arguments));
    }`

I also changed the base code to use v2.

**Comment by dashnullify** [comment]
Hm weird
